/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Before;
import org.junit.BeforeClass;

public class LibraryTest {
	
   
   static WebDriver driver;
   
   @BeforeClass
   public static  void openBrowser() {
	   
	   driver = new ChromeDriver();
	  // driver = new FirefoxDriver();
	   driver.manage().window().maximize();
	   
     	
   }
   @Test
   public void ChromeTest() throws InterruptedException {
	   
	  /* String linkurl = "https://en.wikipedia.org/wiki/Main_Page";
	   String search = "FIFA_World_Cup";
	   String bar = "search";
	   String button = "button";
	   String xpathlink = "//*[@id=\"mw-content-text\"]/div/p[1]/a";
	   String idtitle = "firstHeader";
	   
	   driver.get(linkurl);
	   driver.findElement(By.name(search)).sendKeys("World Cup");
	   driver.findElement(By.id(button)).click();
	   driver.findElement(By.xpath(xpathlink)).click();
	   WebElement title = driver.findElement(By.id("idtitle"));*/
	   
	   /*WebDriver driver = new ChromeDriver();
	   
	   driver.get("https://en.wikipedia.org/wiki/Main_Page");
	   
	   WebElement barreRecherche = driver.findElement(By.id("SerchInput"));
	   barreRecherche.sendKeys("World Cup"); 
	   
	   driver.findElement(By.id("searchbutton")).click();
	   
	   List<WebElement> link = (List<WebElement>) driver.findElement(By.xpath("//*[@id=\"mw-content-text\"]/div/p[1]/a"));
	   
	   link.get(0).click();
	   	   
	   Assert.assertEquals("FIFA World Cup", driver.findElement(By.id("firstHeader")));
	   
	   
	  // WebElement imageCoupe = driver.findElement(By.id("dimg_29"));
	  // Assert.assertTrue(imageCoupe.isDisplayed());
	   //imageCoupe.isDisplayed();*/
	   
	  
		Thread.sleep(5000);
	
	  
   }
   
   @AfterClass
   public static  void closeBrowser()
   {
	   driver.quit();
   	
   }
   
   
    
}
